name: Build and Test

on: [push]

jobs:
  build_and_test_matrix:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Run requirements update and output 
        run: |
          bazel run requirements.update
          cat requirements_*.txt
        shell: bash
      - name : Upload updated requirements file
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ matrix.os }}-requirements
          path: requirements_*_lock.txt 
