name: Build and Test

on: [push]

jobs:
  build_and_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Test requirements files
        run: |
          bazel test requirements_test
        shell: bash
      - name: Run requirements update and output 
        run: |
          bazel run requirements.update > requirements_output.txt
        shell: bash
        if: failure()
      - name: Upload updated requirements file
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ matrix.os }}-requirements
          path: requirements_output.txt
        if: failure()
      - name: Run tests
        run: bazel test ...
        shell: bash
      - name: Build example tarballs
        run: | 
          bazel build src:example_no_ui_tar
          bazel build src:example_tar
        shell: bash
      - name: Upload example tarballs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-example-tarballs
          path: |
            bazel-bin/src/example_no_ui_tar.tar

  # Run tarbal on a fresh instance.
  test_tarballs_matrix:
    needs: [build_and_test_matrix]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-example-tarballs
          path: example_no_ui_tar.tar 
      - name: extract and run tarball
        run: |
          tar -xvf example_no_ui_tar.tar -C .
          ./src/example_no_ui.py
